language: ruby
rvm:
  - 1.9.2
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec spinach
before_script:
  - psql -c 'create database purinklecouk_test;' -U postgres