development:
  adapter: postgresql
  encoding: utf8
  database: purinklecouk_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: purinklecouk_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: purinklecouk_production
  pool: 5
  username:
  password:

postgres:
  adapter: postgresql
  database: purinklecouk_test
  username: postgres